### ISSUE TITLE
Colored background bug

### ISSUE THREAD

**Issue by sshsrn** [uday03meh/basketball-score-counter#15]
When the score of the two teams is same, it still shows one in green and one in red, while it should be the same color for both teams as the score is same.

![image](https://user-images.githubusercontent.com/62781914/197094443-aa333795-f273-4ffc-91a9-92ea2b820502.png)

Also, when the score is reset (New game button is pressed), the color remains.

![image](https://user-images.githubusercontent.com/62781914/197094632-9ffad211-b493-4a1d-9622-8a852bd97bea.png)

**Comment by sshsrn** [comment]
Kindly assign this issue to me! @uday03meh.

**Comment by uday03meh** [comment]
Hi, Please change the color to yellow when both the teams have same score.
