### ISSUE TITLE
add Background Image 

### ISSUE THREAD

**Issue by gkumar-pandey** [uday03meh/basketball-score-counter#4]
Hey @uday03meh 
i want to add the below image as a background image with darken background effect to this project
please assign to me  
![markus-spiske-3TrLKf7Jfbo-unsplash](https://user-images.githubusercontent.com/79089330/195435223-843e2607-6e50-400b-ab20-d2e00d6f7731.jpg)

**Comment by uday03meh** [comment]
Hi @gkumar-pandey , Please do make sure that the image does not reduce visibility of other site content.

**Comment by codeansh20** [comment]
Can u assign this task to me
And please let me know in which project u wanna put this

**Comment by ahmd-nish** [comment]
Hi  @gkumar-pandey can you please assign this task to me I have prior experience in doing these types of tasks

**Comment by uday03meh** [comment]
Closed this as a background gif is already added in #11 PR
