### ISSUE TITLE
Code not formatted

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/basketball-score-counter#6]
In instructions part of README, code is not formatted properly using markdown, use 3 "backticks" to solve it

git clone 

### VS

``` git clone ```

![image](https://user-images.githubusercontent.com/59679281/195479930-044b52d2-9899-4c21-af75-a4d12778769e.png)

**Comment by chehe040** [comment]
Hi, I would like to work on this. Please assign this to me.

**Comment by uday03meh** [comment]
Solved with PR #7 by @chehe040
